apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-replicaset
  template:
    metadata:
      labels:
        app: echo-replicaset
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
