apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo-replicaset
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-replicaset
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo-replicaset
  template:
    metadata:
      labels:
        app: echo-replicaset
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
